// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggrwtayxwmcausmgvldg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdncnd0YXl4d21jYXVzbWd2bGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Mjc1MzcsImV4cCI6MjA2NTQwMzUzN30.pykw5bAO4BUds1pYjtJsFK3gCMQ58HJO6vAIuurVvLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);